name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build & Release
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install Rust
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9
        with:
          toolchain: stable

      - name: Install WiX
        run: dotnet tool install --global wix

      - name: Install WiX Extensions
        run: |
          wix eula accept wix7
          wix extension add -g WixToolset.UI.wixext
          wix extension add -g WixToolset.Util.wixext

      - name: Install UPX
        run: choco install upx --no-progress

      - name: Build Optimized Binary
        run: |
          $env:RUSTFLAGS="-C link-arg=/OPT:REF -C link-arg=/OPT:ICF -C link-arg=/INCREMENTAL:NO"
          cargo build --release

      - name: Compress Binary with UPX
        run: upx --best --lzma target\release\pausecat.exe

      - name: Build MSI Installer
        run: |
          wix build wix\main.wxs -ext WixToolset.UI.wixext -ext WixToolset.Util.wixext -o target\release\PauseCat_Installer.msi

      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191
        with:
          files: |
            target/release/PauseCat_Installer.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
